@url = http://localhost:3000/dashboard


POST {{url}}/register
Content-Type: application/json

{
    "name": "Prueba",
    "surname": "Prueba",
    "email": "14@hotmail.com",
    "password": "14",
    "role": "manager",
    "assigned_id_warehouse": 2
}

###

POST {{url}}/login
Content-Type: application/json

{
    "email": "14@hotmail.com",
    "password": "14"
}

###

GET {{url}}/manager
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMjU1MTcwNiwiZXhwIjoxNzMyNTU1MzA2fQ.2zMECn2njV93euk5FGFAy4KFqMhAWeU0--SVNxOqSuI
