@url = http://localhost:3000


POST {{url}}/register
Content-Type: application/json

{
    "name": "Prueba",
    "surname": "Prueba",
    "email": "jijij@hotmail.com",
    "password": "jiji",
    "role": "boss",
    "assigned_id_warehouse": 2
}

###

POST {{url}}/login
Content-Type: application/json

{
    "email": "vaya.suarez@gmail.com",
    "password": "vaya"
}

###

GET {{url}}/manager
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMjY0MTY4OSwiZXhwIjoxNzMyNjQ1Mjg5fQ.FaWYxnPaSgZ6shbzjKp9m7qSbLPS6TsdVqEZDvf-0QQ

