@url = http://localhost:3000/dashboard

POST {{url}}/login
Content-Type: application/json

{
    "email": "marinieves@hotmail.com",
    "password": "2FM:;tDi>1A4"
}

###

GET {{url}}/hola
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VyX3JvbGUiOiJkcml2ZXIiLCJpYXQiOjE3MzI0NjcxNjEsImV4cCI6MTczMjQ3MDc2MX0.6cOxiVUSYYWMrE8vbgGSHJ90IOObo8p1qI3w8D3O2Jw
