@url = http://localhost:3000

POST {{url}}/login
Content-Type: application/json

{
    "email": "ana.ramirez@gmail.com",
    "password": "anaramirez"
}

# Operator
#     "email": "16@hotmail.com"",
#     "password": "16"

# Manager
#     "email": "ana.ramirez@gmail.com",
#     "password": "anaramirez"

# Boss
#     "email": "carlos.lopez@gmail.com",
#     "password": "carloslopez"