@url = http://localhost:3000/boss

// /api/boss/USERS (el post y el put se debe hacer con postman para adjuntar imagen)

// Mostrar todos los usuarios

GET {{url}}/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Mostrar un usuario con su almacen asociado

GET {{url}}/users/66
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzg1ODMwMCwiZXhwIjoxNzMzODYxOTAwfQ.ZSlugb65qaK1a3m_mL8lQ1JN35ASBmTEo0lpADqVClM

###

// Borrar un usuario

DELETE {{url}}/users/66
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzg1ODMwMCwiZXhwIjoxNzMzODYxOTAwfQ.ZSlugb65qaK1a3m_mL8lQ1JN35ASBmTEo0lpADqVClM

// / api/boss/TRUCKS

//Mostrar los camiones que hay disponibles
###

GET {{url}}/available-trucks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

// Mostrar la matricula del camion

###

GET {{url}}/truck/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

// /api/boss/WAREHOUSE (el post y el put se debe hacer con postman para adjuntar imagen)

###

// Mostrar los almacenes disponibles para el manager
GET {{url}}/available-warehouse
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNTYsInVzZXJfbmFtZSI6Ikplc2ljYSIsInVzZXJfc3VybmFtZSI6IlJ1aXoiLCJ1c2VyX3JvbGUiOiJib3NzIiwidXNlcl9wbGF0ZSI6bnVsbCwidXNlcl9pbWFnZSI6InVzZXItMTU2LmpwZyIsImlhdCI6MTczMzk0MTk4NCwiZXhwIjoxNzMzOTQ1NTg0fQ.7gSBQqqkGzl6aK_uHE_zvkD7Bm-f_ctnnwBXV-Laz7A


###

// Mostrar todos los almacenes

GET {{url}}/warehouse
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Mostrar un almacen con sus usuarios asociados

GET {{url}}/warehouse/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Borrar un almacen

DELETE {{url}}/warehouse/23
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzg1ODMwMCwiZXhwIjoxNzMzODYxOTAwfQ.ZSlugb65qaK1a3m_mL8lQ1JN35ASBmTEo0lpADqVClM