@url = http://localhost:3000/boss

// /api/boss/USERS (el post y el put se debe hacer con postman para adjuntar imagen)

// Mostrar todos los usuarios

GET {{url}}/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzA5MTE1OCwiZXhwIjoxNzMzMDk0NzU4fQ.35vNVDbcUCLeR8mP7kUMkIRbP2S1UOsuYwKeXT9s_IY

###

// Mostrar un usuario con su almacen asociado

GET {{url}}/users/60
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzA5MTE1OCwiZXhwIjoxNzMzMDk0NzU4fQ.35vNVDbcUCLeR8mP7kUMkIRbP2S1UOsuYwKeXT9s_IY

###

// Borrar un usuario

DELETE {{url}}/users/61
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzA5MTE1OCwiZXhwIjoxNzMzMDk0NzU4fQ.35vNVDbcUCLeR8mP7kUMkIRbP2S1UOsuYwKeXT9s_IY

// / api/boss/TRUCKS

//Mostrar los camiones que hay disponibles
###

GET {{url}}/trucks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzMzODY1MCwiZXhwIjoxNzMzMzQyMjUwfQ.OaoVdndg38xc8dP4IPTrsCzBkAOL7nYOyshtGmkt1vY

// /api/boss/WAREHOUSE (el post y el put se debe hacer con postman para adjuntar imagen)

###

// Mostrar todos los almacenes

GET {{url}}/warehouse
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzE1Njg1MCwiZXhwIjoxNzMzMTYwNDUwfQ.ihE2Z_9Yr2NpmGn7N1IotQgg__TLj0tUlLb_sdOfeGk

###

// Mostrar un almacen con sus usuarios asociados

GET {{url}}/warehouse/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzE1Njg1MCwiZXhwIjoxNzMzMTYwNDUwfQ.ihE2Z_9Yr2NpmGn7N1IotQgg__TLj0tUlLb_sdOfeGk

###

// Borrar un almacen

DELETE {{url}}/warehouse/14
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzE1Njg1MCwiZXhwIjoxNzMzMTYwNDUwfQ.ihE2Z_9Yr2NpmGn7N1IotQgg__TLj0tUlLb_sdOfeGk