@url = http://localhost:3000/boss

// /api/boss/USERS (el post y el put se debe hacer con postman para adjuntar imagen)

// Mostrar todos los usuarios

GET {{url}}/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Mostrar un usuario con su almacen asociado

GET {{url}}/users/63
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Borrar un usuario

DELETE {{url}}/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

// / api/boss/TRUCKS

//Mostrar los camiones que hay disponibles
###

GET {{url}}/available-trucks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

// Mostrar la matricula del camion

###

GET {{url}}/truck/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

// /api/boss/WAREHOUSE (el post y el put se debe hacer con postman para adjuntar imagen)


###

// Mostrar todos los almacenes

GET {{url}}/warehouse
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Mostrar un almacen con sus usuarios asociados

GET {{url}}/warehouse/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzc3NTQxOCwiZXhwIjoxNzMzNzc5MDE4fQ.E3DTsbHa1Gd0Gi2JaQr3HhoUoU9K0SGIol3A7hXtkOs

###

// Borrar un almacen

DELETE {{url}}/warehouse/25
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NywidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoiYm9zcyIsImlhdCI6MTczMzQ4MTQxOSwiZXhwIjoxNzMzNDg1MDE5fQ.RbkQs_wR2W2m7pzVNn9nVlEFCaS0me2Ztc7TYM_uh6k