@url = http://localhost:3000/manager

// Get outgoing order
GET {{url}}/outgoing-orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzQ4ODA2OCwiZXhwIjoxNzMzNDkxNjY4fQ.Cx9jQCVJx6ZOvc7-jidMgQM7veqH0Ocwwr2vsJQ4C1o

###

// Get incoming orders
GET {{url}}/incoming-orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzE1NjUxNywiZXhwIjoxNzMzMTYwMTE3fQ.LagZzsiWjvymccSfnRk22GC5Eg2HwCgvJINF9wpTR88

###

// Get order details
GET {{url}}/review-order/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzE1NjUxNywiZXhwIjoxNzMzMTYwMTE3fQ.LagZzsiWjvymccSfnRk22GC5Eg2HwCgvJINF9wpTR88

###

// Review outgoing orders
PUT {{url}}/review-order/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzE1NjUxNywiZXhwIjoxNzMzMTYwMTE3fQ.LagZzsiWjvymccSfnRk22GC5Eg2HwCgvJINF9wpTR88

{
    "status": "corrections needed",
    "comments": "Falta 1 palé"
}

###

// Verify incoming orders
PUT {{url}}/verify-order/26
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzQ5MTc2NCwiZXhwIjoxNzMzNDk1MzY0fQ.5S3u1-fXHaEX6S7jgm_WwFH_j8pEOIJjRBvgksvytMo

{
    "status": "not approved",
    "comments": ""
}