@url = http://localhost:3000/manager

// Obtener pedidos de salida
GET {{url}}/outgoing-orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzE0MDk4MCwiZXhwIjoxNzMzMTQ0NTgwfQ.zSYUV9LWDas7NNvDrFzNyn75sL4Dwm30WEKf1K2kdAc

###

// Obtener pedidos de entrada
GET {{url}}/incoming-orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzE0MDk4MCwiZXhwIjoxNzMzMTQ0NTgwfQ.zSYUV9LWDas7NNvDrFzNyn75sL4Dwm30WEKf1K2kdAc

###

GET {{url}}/review-order/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9uYW1lIjoiUHJ1ZWJhIiwidXNlcl9zdXJuYW1lIjoiUHJ1ZWJhIiwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMzE0MDk4MCwiZXhwIjoxNzMzMTQ0NTgwfQ.zSYUV9LWDas7NNvDrFzNyn75sL4Dwm30WEKf1K2kdAc

###

// Actualizar pedidos
PUT {{url}}/review-order/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NCwidXNlcl9yb2xlIjoibWFuYWdlciIsImlhdCI6MTczMjk3NTM4MCwiZXhwIjoxNzMyOTc4OTgwfQ.jf6GRXLDTu5WIrHTAqmTqdlrrQNOUGHHJWi-GCQPB04

{
    "status": "ready for departure",
    "comments": ""
}