@url = http://localhost:3000/operator

GET {{url}}/order-list
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNzgxOTcsImV4cCI6MTczMzA4MTc5N30.fSheilkMhkhgVQJMJDoWZTgFdfnt3YwyQMri3ONKpGQ

###
GET {{url}}/modify-order/22
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNzgxOTcsImV4cCI6MTczMzA4MTc5N30.fSheilkMhkhgVQJMJDoWZTgFdfnt3YwyQMri3ONKpGQ

### Crear un nuevo pedido
POST {{url}}/create-order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNzgxOTcsImV4cCI6MTczMzA4MTc5N30.fSheilkMhkhgVQJMJDoWZTgFdfnt3YwyQMri3ONKpGQ

{
    "send_date": "2024-11-23T12:00:00",        
    "received_date": "2024-11-25T12:00:00",    
    "truck_id_truck": 42,                
    "origin_warehouse_id": 1,             
    "destination_warehouse_id": 3,         
    "status": "pending",                
    "comments": "",
    "products": [
        {
            "product_id": 4,
            "quantity": 12
        },
                {
            "product_id": 5,
            "quantity": 12
        },
                {
            "product_id": 1,
            "quantity": 12
        }
    ]
}


### Modificar pedido
PUT {{url}}/modify-order/26
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNzgxOTcsImV4cCI6MTczMzA4MTc5N30.fSheilkMhkhgVQJMJDoWZTgFdfnt3YwyQMri3ONKpGQ

{
    "send_date": "2024-11-23T12:00:00",        
    "received_date": "2024-11-25T12:00:00",    
    "truck_id_truck": 42,                
    "origin_warehouse_id": 1,             
    "destination_warehouse_id": 3,         
    "status": "pending",                
    "comments": "",
    "products": [
        {
            "product_id": 4,
            "quantity": 12
        },
                {
            "product_id": 5,
            "quantity": 12
        },
                {
            "product_id": 1,
            "quantity": 12
        }
    ]
}

###
DELETE {{url}}/modify-order/87
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNzA4NTksImV4cCI6MTczMzA3NDQ1OX0.Vo9k4Dkt_BRRlajp48XdA-oVcGau2unhTav3KckQleI