@url = http://localhost:3000/operator

GET {{url}}/order-list
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNTY2MzMsImV4cCI6MTczMzA2MDIzM30.DTED4drimULYp464ryb96pNLwJEtZxKrlqbihOoe6a8
###
GET {{url}}/modify-order/42
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNTY2MzMsImV4cCI6MTczMzA2MDIzM30.DTED4drimULYp464ryb96pNLwJEtZxKrlqbihOoe6a8

###
PUT {{url}}/modify-order/42
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNTY2MzMsImV4cCI6MTczMzA2MDIzM30.DTED4drimULYp464ryb96pNLwJEtZxKrlqbihOoe6a8

{
    "send_date": "2024-11-23T12:00:00",        
    "received_date": "2024-11-25T12:00:00",    
    "truck_id_truck": 42,                
    "origin_warehouse_id": 1,             
    "destination_warehouse_id": 3,         
    "status": "pending",                
    "comments": "",
    "products": [
        {
            "product_id": 2,
            "quantity": 79
        },
                {
            "product_id": 1,
            "quantity": 1
        },
                        {
            "product_id": 1,
            "quantity": 1
        }
    ]
}

### Crear un nuevo pedido
POST {{url}}/create-order
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MiwidXNlcl9yb2xlIjoib3BlcmF0b3IiLCJpYXQiOjE3MzMwNDk3NDcsImV4cCI6MTczMzA1MzM0N30.9VMffBLDdpehdOcn6P3exfKX7ZdE0a0QXpW73Gr00Qw

{
    "send_date": "2024-11-23T12:00:00",        
    "received_date": "2024-11-25T12:00:00",    
    "truck_id_truck": 42,                
    "origin_warehouse_id": 1,             
    "destination_warehouse_id": 3,         
    "status": "pending",                
    "comments": "",
    "products": [
        {
            "product_id": 4,
            "quantity": 12
        },
                {
            "product_id": 5,
            "quantity": 12
        },
                {
            "product_id": 1,
            "quantity": 12
        }
    ]
}
